/*
 *
 * GrigliaValutazioni constants
 *
 */

export const GRIGLIA_VALUTAZIONI_URI_FETCH = 'cicero_academy/api/valutazioni/valuta/';
export const GRIGLIA_VALUTAZIONI_URI_CREA = 'cicero_academy/api/valutazioni/valuta/';

export const GRIGLIA_VALUTAZIONI_SPINNER_SET = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_SPINNER_SET';
export const GRIGLIA_VALUTAZIONI_FEEDBACK_SET = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_FEEDBACK_SET';
export const GRIGLIA_VALUTAZIONI_FEEDBACK_RESET = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_FEEDBACK_RESET';
export const GRIGLIA_VALUTAZIONI_DISPLAY_SET = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_DISPLAY_SET';
export const GRIGLIA_VALUTAZIONI_CONTENUTO_SET = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_CONTENUTO_SET';
export const GRIGLIA_VALUTAZIONI_VALUTABILI_FETCH = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_VALUTABILI_FETCH';
export const GRIGLIA_VALUTAZIONI_VALUTABILI_SET = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_VALUTABILI_SET';
export const GRIGLIA_VALUTAZIONI_VALUTABILI_RESET = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_VALUTABILI_RESET';
export const GRIGLIA_VALUTAZIONI_VALUTABILI_SORT = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_VALUTABILI_SORT';
export const GRIGLIA_VALUTAZIONI_VALUTABILI_BLOCCO_SET = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_VALUTABILI_BLOCCO_SET';
export const GRIGLIA_VALUTAZIONI_SELECTION_SET = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_SELECTION_SET';
export const GRIGLIA_VALUTAZIONI_SELECTION_RESET = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_SELECTION_RESET';
export const GRIGLIA_VALUTAZIONI_CREA = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_CREA';
export const GRIGLIA_VALUTAZIONI_RESET = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_RESET';
export const CLASSE_DETTAGLIO_URL_GRIGLIA_VALUTAZIONE_ELIMINA = 'cicero_academy/api/valutazioni/delete/';

// dettaglio
export const GRIGLIA_VALUTAZIONI_DETTAGLIO_SET = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_DETTAGLIO_SET';
export const GRIGLIA_VALUTAZIONI_DETTAGLIO_RESET = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_DETTAGLIO_RESET';
export const GRIGLIA_VALUTAZIONI_DETTAGLIO_FETCH = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_DETTAGLIO_FETCH';
export const GRIGLIA_VALUTAZIONI_DETTAGLIO_SORT = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_DETTAGLIO_SORT';
export const GRIGLIA_VALUTAZIONI_DETTAGLIO_STUDENTE_FETCH = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_DETTAGLIO_STUDENTE_FETCH';
export const GRIGLIA_VALUTAZIONI_DETTAGLIO_STUDENTE_SET = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_DETTAGLIO_STUDENTE_SET';
export const GRIGLIA_VALUTAZIONI_DETTAGLIO_STUDENTE_RESET = 'app/GrigliaValutazioni/GRIGLIA_VALUTAZIONI_DETTAGLIO_STUDENTE_RESET';
export const GRIGLIA_VALUTAZIONI_URI_DETTAGLIO = 'cicero_academy/api/valutazioni/explode/';
export const GRIGLIA_VALUTAZIONI_URI_DETTAGLIO_STUDENTE = 'cicero_academy/api/valutazioni/explode/{ID_VALUTAZIONE}/studente';
